### ISSUE TITLE
Think about centralized ACL

### ISSUE THREAD

**Issue by Jasopaum** [arkhn/identity-provider#11]

**Comment by simonvadee** [comment]
See:
- https://github.com/ory/kratos ("API-first Identity and User Management system")
- https://github.com/ory/keto ("a permission server that implements best practice access control mechanisms")
- https://github.com/ory/oathkeeper (" Identity & Access Proxy (IAP) and Access Control Decision API that authorizes HTTP requests based on sets of Access Rules")

**Comment by simonvadee** [comment]
Each service will keep enforcing its own permissions right now because it's a lot of change in the codebase/architecture to centralize ACL and the stack is not stable enough to make the move right now.
Let's rediscuss this in a few months
